# this is travis script for testing Fceumm-ps2 compilation

sudo: required

install:
 ## Dependencies
- sudo apt-get install -yqqq gcc-4.4 patch wget make git libc6-dev zlib1g zlib1g-dev libucl1 libucl-dev
 ## ps2dev

services:
  - docker
  
env:
  matrix:
    - CDSUPPORT=0 CDNAME=
    - CDSUPPORT=1 CDNAME=cdvdsupport

before_script:
# Get docker image
  - docker pull akuhak/ps2toolchain:latest
  - docker ps

# Run DOCKER, run!
  - docker run -d akuhak/ps2toolchain bash -c "while true; do sleep 5; done" > container_id

# Configure ps2sdk
  - docker exec -t $(cat container_id) bash -c "ls -l"
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/ps2dev/ps2sdk"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk/; make --silent install"

# installing ports
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/ps2dev/ps2sdk-ports"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk-ports/zlib/; make install"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk-ports/libpng/; make install"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk-ports/libjpeg/; make install"

# Set up the gsKit
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/ps2dev/gsKit /gsKit/"
  - docker exec -t $(cat container_id) bash -c "cd /gsKit/; make install"

# Set up the ps2packer
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/ps2dev/ps2-packer"
  - docker exec -t $(cat container_id) bash -c "cd /ps2-packer/; make; make install"

# Copy source code
  - cd $TRAVIS_BUILD_DIR
  - docker cp $TRAVIS_BUILD_DIR $(cat container_id):/

script:
  - docker exec -t $(cat container_id) bash -c "cd /Fceumm-PS2/; make -f Makefile.ps2"
  - docker cp $(cat container_id):/ $TRAVIS_BUILD_DIR 
  - zip Fceumm-ps2_$TRAVIS_COMMIT_$CDNAME.zip fceu-packed.elf
  - curl --upload-file Fceumm-ps2_$TRAVIS_COMMIT_$CDNAME.zip https://transfer.sh/Fceumm-ps2_$TRAVIS_COMMIT_$CDNAME.zip | grep transfer
