#deploy:
  #provider: releases
  #api_key:
    #secure: SPp1uPVV7eUJQbP2e6fM9Mv0FSPDO1xUSX4De1VFUHg8AwIjbfNHVaPTN1ZEX/OQqujwNJYwoW/GwF2ZsIXwElROm3gLLVjL0cTIVZeK/GfQa5fZpCNLDYERug3pr73XIes0W2C7dOn2EuqCMGszTgZuDDjDHkZApgxQ+JKg+LRowzliFeLUkOYkoiBII0umhuQZS9A2Ars92mLpekUl6IQpqHRFJNPVgFgooRGwvsLikVwuRau7C5OQP53iaye4Q6/azg9oAgMJHU9z2KQrshdbecBlYAzICC8EaFsEWyDBvxotGhlKQilyYgQZwYCLkYkwmdoKF6C0NeJhfFjgVX1DhkF4ASdoMd1wOAb+9X6uy+3et7K2L/qgnBt+UUVlYR5/0lA34Sr0f4xdvJXoG15s/H0v/yQmPN7Y35+0AOob0EYNeisArDzVFKWTbii1h7IIbDqOybOyPsAdReOkrAXiP9D03IB2sFGXvi1Kr8VUyB2SM0dhQ5uoBMoCapm2RF0QXhaKWujqhg/QOji0n3/SbnZo44sPcaXQjQNo3YGBZn4H8Y+VbAdaDBKGU74k14YeYjk2s8n8JF8C23PO9hU36lQLGuTk1Oeq/Fv7uMydkxVrdwTwVw6YuMJ9AevKIIYVA10EVN2/s0Jk6eIfQuAsIVYFpveT3zha1lsThkM=
  #file: test
  #on:
#tags: true
    #repo: AKuHAK/Fceumm-PS2
    #branch: AKuHAK-patch-1

# this is travis script for testing Fceumm-ps2 compilation
# upload in releases if branch is tagged
#deploy:
#  - provider: releases
#    api_key: $APIKEY
#    file: $TRAVIS_BUILD_DIR/fceu-packed.$TRAVIS_COMMIT$CDNAME.elf
 # skip_cleanup: true
  #on:
   # tags: true
    #all_branches: true
    
   deploy:
      provider: releases
      api_key:
        secure: SPp1uPVV7eUJQbP2e6fM9Mv0FSPDO1xUSX4De1VFUHg8AwIjbfNHVaPTN1ZEX/OQqujwNJYwoW/GwF2ZsIXwElROm3gLLVjL0cTIVZeK/GfQa5fZpCNLDYERug3pr73XIes0W2C7dOn2EuqCMGszTgZuDDjDHkZApgxQ+JKg+LRowzliFeLUkOYkoiBII0umhuQZS9A2Ars92mLpekUl6IQpqHRFJNPVgFgooRGwvsLikVwuRau7C5OQP53iaye4Q6/azg9oAgMJHU9z2KQrshdbecBlYAzICC8EaFsEWyDBvxotGhlKQilyYgQZwYCLkYkwmdoKF6C0NeJhfFjgVX1DhkF4ASdoMd1wOAb+9X6uy+3et7K2L/qgnBt+UUVlYR5/0lA34Sr0f4xdvJXoG15s/H0v/yQmPN7Y35+0AOob0EYNeisArDzVFKWTbii1h7IIbDqOybOyPsAdReOkrAXiP9D03IB2sFGXvi1Kr8VUyB2SM0dhQ5uoBMoCapm2RF0QXhaKWujqhg/QOji0n3/SbnZo44sPcaXQjQNo3YGBZn4H8Y+VbAdaDBKGU74k14YeYjk2s8n8JF8C23PO9hU36lQLGuTk1Oeq/Fv7uMydkxVrdwTwVw6YuMJ9AevKIIYVA10EVN2/s0Jk6eIfQuAsIVYFpveT3zha1lsThkM=
      file: $TRAVIS_BUILD_DIR/fceu-packed.$TRAVIS_COMMIT$CDNAME.elf
      skip_cleanup: true
      on:
        tags: true
        #all_branches: true
        branch: AKuHAK-patch-1
 

sudo: required

install:
 ## Dependencies
- sudo apt-get install -yqqq gcc-4.4 patch wget make git libc6-dev zlib1g zlib1g-dev libucl1 libucl-dev
 ## ps2dev

services:
  - docker
  
env:
  matrix:
  - CD=0 CDNAME=
  - CD=1 CDNAME=cdvdsupport

before_script:
# Get docker image
  - docker pull akuhak/ps2toolchain:latest
  - docker ps

# Run DOCKER, run!
  - docker run -d akuhak/ps2toolchain bash -c "while true; do sleep 5; done" > container_id

# Configure ps2sdk
  - docker exec -t $(cat container_id) bash -c "ls -l"
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/ps2dev/ps2sdk"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk/; make install --silent"

# installing ports
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/ps2dev/ps2sdk-ports"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk-ports/zlib/; make install"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk-ports/libpng/; make install"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk-ports/libjpeg/; make install"

# Set up the gsKit
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/ps2dev/gsKit /gsKit/"
  - docker exec -t $(cat container_id) bash -c "cd /gsKit/; make install"

# Set up the ps2packer
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/ps2dev/ps2-packer"
  - docker exec -t $(cat container_id) bash -c "cd /ps2-packer/; make; make install"

# Copy source code
  - cd $TRAVIS_BUILD_DIR
  - docker cp $TRAVIS_BUILD_DIR $(cat container_id):/

script:
  - docker exec -t $(cat container_id) bash -c "cd /Fceumm-PS2/; make -f Makefile.ps2 CDSUPPORT=$CD"
  - docker cp $(cat container_id):/Fceumm-PS2/fceu-packed.elf $TRAVIS_BUILD_DIR/fceu-packed.$TRAVIS_COMMIT$CDNAME.elf
  - curl --upload-file fceu-packed.$TRAVIS_COMMIT$CDNAME.elf https://transfer.sh/fceu-packed.$TRAVIS_COMMIT$CDNAME.elf | grep transfer
